### ISSUE TITLE
">hen" command

### ISSUE THREAD

**Issue by Justin-Mulligan** [Kyle-Stadelmann/DiscordBot#17]
# Legacy Idea
Type: Utility
Idea: >hen to plan events/games or smthn with poll or planner? idk

---

**Comment by Kyle-Stadelmann** [comment]
Tweed originally submitted this idea in response to zach mentioning this idea: https://github.com/Kyle-Stadelmann/DiscordBot/issues/53. Marking as duplicate and closing
