### ISSUE TITLE
use dynamo "TTL" to automatically check dates for cooldown

### ISSUE THREAD

**Issue by Justin-Mulligan** [Kyle-Stadelmann/DiscordBot#23]
# Legacy Idea
Type: General
Idea: TTL on cd = cd date

---

**Comment by Kyle-Stadelmann** [comment]
For more information: Cooldowns currently use a `date` field which represents the date and time for when the cooldown is over for a user + cmd pair. DynamoDB seems to have an option for "time to live" (TTL) for db entries. So this task is to research if using TTL would be a better solution than what we currently have, and implement it if that's true
